# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truffe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedcreditcard',
            name='name',
            field=models.CharField(default=b'---', max_length=255, unique=True),
        ),
    ]
