# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingline',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_core.Account', verbose_name='Compte'),
        ),
    ]
