# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_main', '0002_auto_20201104_1311-3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(default=b'---', max_length=255, verbose_name='Titre du budget'),
        ),
    ]
