#!/bin/sh

# (C) AGEPoly (Association Générale des Etudiants de l’EPFL)
#     Téo Goddet, 2020
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# this line here is what we should have to get rid of the hard link error
touch /etc/crontab /etc/cron.d/truffe2

exec cron -f >> /var/log/truffe2/cron.log 2>&1