# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbookline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_core.Account', verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='cashbookline',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='expenseclaimline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_core.Account', verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='expenseclaimline',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='add_to',
            field=models.BooleanField(default=False, verbose_name='Rajouter "\xc0 l\'attention de"'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='TVA'),
        ),
        migrations.AlterField(
            model_name='providerinvoiceline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_core.Account', verbose_name='Compte'),
        ),
        migrations.AlterField(
            model_name='providerinvoiceline',
            name='tva',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='TVA'),
        ),
    ]
