# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default=b'---', max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(default=b'---', max_length=255),
        ),
    ]
