#!/bin/sh

# (C) AGEPoly (Association Générale des Etudiants de l’EPFL)
#     Roosembert Palacios, 2019
#     Téo Goddet, 20109
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# This program starts apache2 without forking

if ! apache2ctl configtest; then
    return 2
fi

# the path to the environment variable file
test -z "$APACHE_ENVVARS" && APACHE_ENVVARS="/etc/apache2/envvars"
# pick up any necessary environment variables
if test -f "$APACHE_ENVVARS"; then
    # shellcheck source=/dev/null
    . "$APACHE_ENVVARS"
fi

exec /usr/sbin/apache2 -DFOREGROUND -k start
