#!/bin/sh

# (C) AGEPoly (Association Générale des Etudiants de l’EPFL)
#     Roosembert Palacios, 2019
#     Téo Goddet, 2019
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# This program continuously reads truffe2 various logs

exec tail -F /var/log/apache2/error.log /var/log/apache2/access.log /var/log/celery/celery.log /var/log/truffe2/django.log /var/log/truffe2/cron.log  /var/log/rabbitmq/rabbit\@localhost.log

