# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default=b'---', max_length=255, verbose_name='Nom du compte'),
        ),
        migrations.AlterField(
            model_name='accountcategory',
            name='name',
            field=models.CharField(default=b'---', max_length=255, verbose_name='Nom de la cat\xe9gorie'),
        ),
        migrations.AlterField(
            model_name='accountingyear',
            name='name',
            field=models.CharField(default=b'---', max_length=255, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(default=b'---', max_length=255, verbose_name='Nom du centre de co\xfbt'),
        ),
        migrations.AlterField(
            model_name='tva',
            name='name',
            field=models.CharField(default=b'---', max_length=255, verbose_name='Nom de la TVA'),
        ),
    ]
